---
- name: timestamp create
  hosts:
    - localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: save timestamp
      set_fact:
        timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':', '-') }}"

- name: save configurations from device
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    config_dir: "config_backups/{{ hostvars.localhost.timestamp }}"
    config_filename: "{{ config_dir }}/{{ inventory_hostname }}.conf"
    connection_settings:
      host: "{{ ansible_host }}"
      user: edi
      passwd: Embe1mpls

  tasks:
    - name: create config back directory
      file:
        path: "{{ config_dir }}"
        state: directory
      run_once: yes
      delegate_to: localhost

    - name: save device config
      juniper_junos_config:
        provider: "{{ connection_settings }}"
        dest: "{{ config_filename }}"
        format: text
        retrieve: committed
