---
role: leaf
router_id: 11.2.0.1

interfaces:
  - name: xe-0/0/0.0
    address_family: inet
    ip_address: 11.0.0.1/31
    description: connecting to spine-01
  - name: xe-0/0/1.0
    address_family: inet
    ip_address: 11.0.0.9/31
    description: connecting to spine-02
  - name: xe-0/0/2.0
    address_family: ethernet-switching
    interface-mode: access
    vlan_members: 100
    description: connecting to server-01
  - name: xe-0/0/3.0
    address_family: ethernet-switching
    interface-mode: access
    vlan_members: 100
    description: connecting to server-02
  - name: lo0.0
    address_family: inet
    ip_address: 11.2.0.1/32
    description: loopback address

as: 66001
underlay:
  protocols: ebgp
  neighbors:
    - neighbor_address: 11.0.0.0
      neighbor_as: 65001
      description: to-spine-01
    - neighbor_address: 11.0.0.8
      neighbor_as: 65002
      description: to-spine-02
overlay:
  protocls: ibgp
  route-reflector: no
  overlay-as: 65005
  local-address: 11.2.0.1
  neighbors:
    - neighbor_address: 11.1.0.1
      description: to-spine-01
    - neighbor_address: 11.1.0.2
      description: to-spine-02



vlans:
  - vlan_name: vlan100
    vlan_id: 100
    vxlan_vni: 100
    ingress-node-replication: yes
  - vlan_name: vlan200
    vlan_id: 200
    vxlan_vni: 200
    ingress-node-replication: yes

communities:
  - community_name: cust100
    community_member: target:10001:1