---
role: spine
router_id: 11.1.0.2
interfaces:
  - name: xe-0/0/0.0
    address_family: inet
    ip_address: 11.0.0.10/31
    description: connecting to leaf-02
  - name: xe-0/0/1.0
    address_family: inet
    ip_address: 11.0.0.8/31
    description: connecting to leaf-01
  - name: xe-0/0/2.0
    address_family: inet
    ip_address: 11.0.0.14/31
    description: connecting to leaf-04
  - name: xe-0/0/3.0
    address_family: inet
    ip_address: 11.0.0.12/31
    description: connecting to leaf-03
  - name: xe-0/0/4.0
    address_family: inet
    ip_address: 172.15.15.102/24
    description: private99
  - name: lo0.0
    address_family: inet
    ip_address: 11.1.0.2/32
    description: loopback address

lldp_interfaces:
  - name: xe-0/0/0
  - name: xe-0/0/1
  - name: xe-0/0/2
  - name: xe-0/0/3
  
as: 65002
underlay:
  protocols: ebgp
  neighbors:
    - neighbor_address: 11.0.0.9
      neighbor_as: 66001
      description: to-leaf-01
    - neighbor_address: 11.0.0.11
      neighbor_as: 66002
      description: to-leaf-02
    - neighbor_address: 11.0.0.13
      neighbor_as: 66003
      description: to-leaf-03
    - neighbor_address: 11.0.0.15
      neighbor_as: 66004
      description: to-leaf-04
overlay:
  protocols: ibgp
  route-reflector: yes
  cluster-id: 1.1.1.1
  overlay-as: 65005
  local-address: 11.1.0.2
  neighbors:
    - neighbor_address: 11.2.0.1
      description: to-leaf-01
    - neighbor_address: 11.2.0.2
      description: to-leaf-02
    - neighbor_address: 11.2.0.3
      description: to-leaf-03
    - neighbor_address: 11.2.0.4
      description: to-leaf-04